# Generated by Django 2.2.4 on 2019-10-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
