# Generated by Django 2.2.4 on 2019-10-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0002_auto_20191004_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='image',
            field=models.ImageField(default=1200, upload_to='images/'),
            preserve_default=False,
        ),
    ]
